export const GET_CAT_IMG_FOR_VOTING = 'GET_CAT_IMG_FOR_VOTING';
export const SEND_VOTE = 'SEND_VOTE';

export const GET_BREEDS = 'GET_BREEDS';

export const GET_BREED_DETAILS = 'GET_BREED_DETAILS';

export const GET_SEARCH_BREEDS = 'GET_SEARCH_BREEDS';
export const GET_SEARCH_CATEGORIES = 'GET_SEARCH_CATEGORIES';
export const GET_SEARCH_IMAGES = 'GET_SEARCH_IMAGES';