export const SET_CAT_VOTE_IMG_LOADING_STATUS = 'SET_CAT_VOTE_IMG_LOADING_STATUS';
export const GET_CAT_IMG_FOR_VOTING_SUCCESS = 'GET_CAT_IMG_FOR_VOTING_SUCCESS';

export const SET_BREEDS_LOADING_STATUS = 'SET_BREEDS_LOADING_STATUS';
export const GET_BREEDS_SUCCESS = 'GET_BREEDS_SUCCESS';

export const SET_BREEDS_DETAILS_LOADING_STATUS = 'SET_BREEDS_DETAILS_LOADING_STATUS';
export const GET_BREED_DETAILS_SUCCESS = 'GET_BREED_DETAILS_SUCCESS';

export const SET_SEARCH_IMAGES_LOADING_STATUS = 'SET_SEARCH_IMAGES_LOADING_STATUS';
export const GET_SEARCH_BREEDS_SUCCESS = 'GET_SEARCH_BREEDS_SUCCESS';
export const GET_SEARCH_CATEGORIES_SUCCESS = 'GET_SEARCH_CATEGORIES_SUCCESS';
export const GET_SEARCH_IMAGES_SUCCESS = 'GET_SEARCH_IMAGES_SUCCESS';